### ISSUE TITLE
there's no Markov Chains in this project....

### ISSUE THREAD

**Issue by johndpope** [Honors/Tuno#1]

**Comment by mattneary** [comment]
As you can probably tell it wasn't fully developed. However, I believe I did at least come close to implementing a Markov Chain. Namely, probabilistic progression through the state space of last.fm recommendations. I've not looked at this code in quite awhile though.

**Comment by johndpope** [comment]
hey @mattneary - thanks for your efforts here. 
I'm doing some spring cleaning and closing out old github tickets.
